CREATE TABLE cnpjs AS SELECT CONCAT(LPAD(CNPJ,8,'0')) AS CNPJ FROM default.csv WHERE CNPJ!='' GROUP BY CNPJ ORDER BY CNPJ;

INSERT OVERWRITE DIRECTORY 's3://exercicio04/output/cnpjs'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ';'
SELECT * FROM cnpjs;