{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TOP 3 INSTITUICOES COM MAIS RECLAMACOES (CSV)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT InstituicaoFinanceira,CNPJ,QuantidadeReclamacoesReguladasProcedentes\nFROM csv\nWHERE CNPJ != \"\" AND InstituicaoFinanceira!=\"\"\nGROUP BY InstituicaoFinanceira\nORDER BY QuantidadeReclamacoesReguladasProcedentes DESC\nLIMIT 3"
    }
   ]
  },
  {
   "title": "CNPJ e QTD SERVICOS (API consolidade - adicao de CNPJ)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT CNPJ, COUNT(Servico)\nFROM apidadoscoletados\nWHERE CNPJ!=\"\"\nGROUP BY CNPJ\nORDER BY COUNT(Servico) desc\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "CNPJ (API consolidada - add CNPJ + CSV) & QuantidadeReclamacoesReguladasProcedentes (CSV) & ValorMaximo (API)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT CNPJ, InstituicaoFinanceira,QuantidadeReclamacoesReguladasProcedentes,ValorMaximo FROM csvapidadoscoletados\nWHERE CNPJ!=\"\"\nGROUP BY CNPJ\nORDER BY QuantidadeReclamacoesReguladasProcedentes DESC\nLIMIT 5"
    }
   ]
  }
 ]
}